### ISSUE TITLE
Find a cloud service

### ISSUE THREAD

**Issue by jacobhillock** [COSC481W-2020Fall/cosc481w-581-2020-fall-convoluted-classifiers#50]
- [x] Find a suitable cloud service
 - [x] Find out which AWS items will be used - Baylie, Karen, & Jacob (Oct 12)
   - [x] Have documentation for a cloud structure

**Comment by sjiang1** [comment]
The "find a suitable cloud service" task is very similar to Epic 2: Integrate Code with App #41?

**Comment by baylieburkowski** [comment]
This issue has been completed.
