### ISSUE TITLE
 Get a cropped image of just the dog - Cassie (Oct 12)

### ISSUE THREAD

**Issue by baylieburkowski** [COSC481W-2020Fall/cosc481w-581-2020-fall-convoluted-classifiers#51]
Test cases:
- [x] Our backend program is run using a single image file and an image of a cropped dog is returned in the .outputs file.
- [x] Our backend program is run using a file directory with multiple image files and the images of cropped dogs are returned in the .outputs file.

**Comment by sjiang1** [comment]
looks good.
