### ISSUE TITLE
Research how to get dog breeds - Yao (Oct 19)

### ISSUE THREAD

**Issue by baylieburkowski** [COSC481W-2020Fall/cosc481w-581-2020-fall-convoluted-classifiers#52]
SubTasks:
- [x] Download images - Jacob (Oct12)
- [x] Incorporate into classification model - Yao (Oct 19)

Test Cases:
- [x] Markdown document is written with listed research on how to obtain dog breeds.
- [x] Images have been downloaded

**Comment by sjiang1** [comment]
The test cases are clear.

**Comment by sjiang1** [comment]
There are no test cases for:

> Incorporate into classification model - Yao (Oct 19)
