### ISSUE TITLE
Upload Code (Nov 02)

### ISSUE THREAD

**Issue by jacobhillock** [COSC481W-2020Fall/cosc481w-581-2020-fall-convoluted-classifiers#53]
Sub Tasks:
 - [x] Upload Code to cloud (Nov 2)
 
Test Cases:
- [x] Documentation about where the code lives
- [x] Documentation about how the code will be executed

**Comment by sjiang1** [comment]
What's the difference between uploading code and uploading models?

**Comment by Junyao-S** [comment]
> What's the difference between uploading code and uploading models?

Based on my understand,
In this task, we would make sure the model working with cloud service and the mobile app front end.
In the #54 , we will test the model and the cloud service corresponding with our model should be working well.

**Comment by sjiang1** [comment]
> > What's the difference between uploading code and uploading models?
> 
> Based on my understand,
> In this task, we would make sure the model working with cloud service and the mobile app front end.
> In the #54 , we will test the model and the cloud service corresponding with our model should be working well.

Thanks!
