### ISSUE TITLE
Obtain Models (Oct 26)

### ISSUE THREAD

**Issue by jacobhillock** [COSC481W-2020Fall/cosc481w-581-2020-fall-convoluted-classifiers#56]
Sub Tasks
- [x] Find Detection Model (Oct 26)(Jacob)
- [x] Find Classification model
  - [x] Prepare training dataset (Oct 19)
  - [x] Find a way to train (Oct 26)
  - [x] Compare different models (Oct 26)

Test Cases:
Detection Model
  - [x] Documentation about where it is from
  - [x] Documentaion about why that one

Classification Model
  - [ ] Documentation about where it is from
  - [ ] Documentaion about why that one

**Comment by sjiang1** [comment]
Any task is due Oct. 12 in this issue?

**Comment by jacobhillock** [comment]
> Any task is due Oct. 12 in this issue?

There is not
