### ISSUE TITLE
Display cropped dog image and breed in mobile app - Baylie & Karen (Nov 16)

### ISSUE THREAD

**Issue by baylieburkowski** [COSC481W-2020Fall/cosc481w-581-2020-fall-convoluted-classifiers#57]
SubTasks:
  - [x] Create area for the display cropped picture and breed of dog in the mobile app - Baylie & Karen 
  - [x] Display breed of dog in the mobile app - Baylie & Karen (Nov 16)
  - [x] Display image of the dog in the mobile app - Baylie & Karen (Nov 9)

Test Cases:
- [x] Demonstrate the areas where we have created a spot for the image taken to be displayed and where the dog breed will be displayed
- [x] When a picture is taken within the mobile app it will return, the breed of the dog in the area we created.
- [x] When a picture is taken within the mobile app it will return, the dog image in the area we created.

**Comment by sjiang1** [comment]
the test cases are clear.
are all the tasks here due Oct. 12?

**Comment by baylieburkowski** [comment]
Currently, the due date is unmarked for these items.
