### ISSUE TITLE
 Upload and integrate App to the cloud

### ISSUE THREAD

**Issue by Junyao-S** [COSC481W-2020Fall/cosc481w-581-2020-fall-convoluted-classifiers#58]
Subtasks:
- [ ] upload and integrate

Test cases:
- [ ] App is running and working properly with cloud service

**Comment by Junyao-S** [comment]
should we close this issue since it is similar to the #60 ?

**Comment by baylieburkowski** [comment]
Similar to issue #60 so I am closing
