### ISSUE TITLE
Add comments to android app code - Baylie & Karen (Nov 23)

### ISSUE THREAD

**Issue by kcouch3** [COSC481W-2020Fall/cosc481w-581-2020-fall-convoluted-classifiers#59]
- [x] Add comments to code
     - [x] Comments to android app code for Amplify initialization - Baylie & Karen (Oct 19)
     - [x] Comments to android app code for the REST API & Unit Tests - Baylie & Karen (Oct 26)
     - [x] Comments to android app code for the UI design - Baylie & Karen (Nov 23)

Test Cases: 
- [x] Demonstrate the areas where comments have been added to the .java and manifest files

**Comment by sjiang1** [comment]
looks good.
